### ISSUE TITLE
cannot open caja - upgrade to 1.15

### ISSUE THREAD

**Issue by carlzoo** [mate-desktop/debian-packages#92]
I filed an issue here: https://github.com/mate-desktop/caja/issues/638 but I was told to go to this place instead.

**Comment by raveit65** [comment]
Sorry, please use debian bug reporting system.
Not github.

**Comment by glaubitz** [comment]
No, please don't report that issue in Debian either. We know that Mate is currently broken in Debian and there is no point in reporting the same issue over and over again.

The culprit is that Debian testing/unstable currently ships a development version of gtk+3.0, see: https://sunweavers.net/blog/node/45

**Comment by raveit65** [comment]
Than stop your users to steal our time and spam my mailbox if you don't want to use development releases.
Switching to gtk3 and not using and honnor our latest releases is complete mad.
Why it's called debian-testing if you don't want to test anything ;)

**Comment by glaubitz** [comment]
I'm on the same boat with you. I'm annoyed by these people as well but there is nothing you can do to prevent ignorant people from bug trackers.

The problem is that many users don't understand the difference between a bug tracker and a support forum and abuse bug trackers for filing support requests. A knowledgeable user will inform themselves about current issues in a **development release** of Debian and not file duplicate bug reports. However, many users aren't really knowledgeable but still use development releases.

I'm all for restricting access to Debian's bug tracker to avoid such spam but so far I have been unsuccessful with that. I also agree that it was a stupid idea to upload a development version of gtk+3.0 to Debian unstable but I wasn't the one to decide that.

In any case, just close such bug reports and tell people that we know stuff is broken and if they want stuff that's not broken, they shouldn't be using a development release of Debian.

I'm also a MATE member on github, btw.

**Comment by Michael-AU** [comment]
This thread probably wouldn't exist if things were explained to the OP correctly. Not everyone understands English at the same level. Don't get angry with people who are trying to get help but also to help the developers and maintainers by reporting problems. Doing so just alienates them and pushes them to other systems.
